model:
  type: "UNetr"
  hyperparam:
    spatial_dims: 3
    in_channels: 1
    out_channels: 2
    img_size: [48, 48, 48]
    feature_size: 8
    hidden_size: 1536
    mlp_dim: 3072
    num_heads: 48
    pos_embed: "conv"
    norm_name: "instance"
    res_block: True
  optimizer:
    type: "AdamW"
    learning_rate: 0.00001
  metric:
    type: "DiceLoss"
    include_background: False
    softmax: True
    reduction: "mean"
  batch_size: 1
  epochs: 1500
