model:
  type: "UNet"
  hyperparam:
    spatial_dims: 3
    in_channels: 1
    out_channels: 2
    channels:  [16, 32, 16, 8]
    strides: [2, 2, 2]
    num_res_units: 2
    norm: "BATCH"
  optimizer:
    type: "Adam"
    learning_rate: 0.0001
  metric:
    type: "DiceLoss"
    include_background: False
    softmax: True
    reduction: "mean"
  batch_size: 1
  epochs: 1500
