#!/bin/bash

#SBATCH --nodes=1
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --time=4:05:00
#SBATCH --mem=20GB
#SBATCH --cpus-per-gpu=4

cd /home/adnanzai/monai-train
ml purge
module load python/3.11 poetry

source $(poetry env info --path)/bin/activate
#python -m monai-ops --optuna ./example/optuna_config.yaml --data=/home/adnanzai/mice_data_v2 --output /home/adnanzai/optuna --seed 0
monai-train --data=/nfs/turbo/dent-tomers/Jonathan/MonaiPipelineData --output=./output --split=0.8 --lr=0.0001 --epochs=500 --batch=1 --seed=0 --savemodel=True --model=/home/adnanzai/monai-train/example/model_unet.yaml

